[package]
name = "nelder-mead"
version = "0.2.0"
authors = ["Antony Lesage <lesage.antony@gmail.com>"]
edition = "2021"

[dependencies]
num-traits = "0.2"

[dependencies.array]
git = "https://github.com/antonylsg/array-rs"
